### ISSUE TITLE
Please Release

### ISSUE THREAD

**Issue by pinage404** [clj-commons/kibit#254]
Hi,

i followed the documentation to use with deps.edn https://github.com/clj-commons/kibit/blob/93a9ce52aaf7761a97528d0b4d412408d09d12a1/README.md?plain=1#L138

but i get the error
`Namespace kibit.driver loaded but function not found: exec` 

https://gitlab.com/pinage404/nix-sandboxes/-/commit/ea962cb385eecbbf1841864b06911ba1b6958a38

---

i guess this is because the last released version doesn't contain the `exec` function

https://github.com/clj-commons/kibit/blob/0.1.8/kibit/src/kibit/driver.clj

which has been added since https://github.com/clj-commons/kibit/pull/252

**Comment by NoahTheDuke** [comment]
I'll try to cut a release soon. Until then, you can use kibit as a git dependency with {:git/url "..." :git/sha "..."} to use the latest commit.

**Comment by SmetDenis** [comment]
Hello @NoahTheDuke 

I apologize for rushing you and for this question.
How are you getting on with your release preparations?

**Comment by NoahTheDuke** [comment]
Thank you for everyone's patience. I've released kibit version 0.1.10 and once I'm added to the right clojars group, I'll release lein-kibit 0.1.10 as well (hopefully tomorrow).

**Comment by pinage404** [comment]
Thanks for the release !
